### ISSUE TITLE
On drag display gets damaged

### ISSUE THREAD

**Issue by jackdeguest** [jebaird/dragtable#30]
Hello Jesse,

I have a table with fixed header, which is achieved using 'display: block', and upon performing the dragging of a column, the column display gets distorted.
I could send you my project for you to have a look at in a pm.

Regards,
Jacques
![bug-after](https://cloud.githubusercontent.com/assets/10134208/5913959/47880a3c-a630-11e4-9103-1b9eff930235.png)
![bug-before](https://cloud.githubusercontent.com/assets/10134208/5913960/479263a6-a630-11e4-990c-43fd52239d88.png)

**Comment by jebaird** [comment]
Howdy! If you setup a jsfiddle/jsbin/codepen of your table + css, I'll be more than happy to take a look at it

**Comment by jackdeguest** [comment]
Thak you Jesse!
Here is a fiddle: http://jsfiddle.net/jackdeguest/81o3roLv/
Additionally, it would be nice to be able to have 2 type of cursor: 1) when the mouse is down (-webkit-grab) and one when the moving is ongoing (-webkit-grabbing)
Also, I am using the table sorting utility (jquery.tablesorter.js) from Christian Bach (http://tablesorter.com) and is it possible to have some timeout before the dragging kicks in so as to differentiate between a click on the header for sorting vs one for dragging?

**Comment by jebaird** [comment]
It appears that the col group is messing with the table display. see http://jsfiddle.net/jebaird/hLp3abzL/ 

![](http://i.imgur.com/mi7pSe8.png)

Commenting them out seems to fix the issue's you're experiencing. 

As for the cursors, its possible to achieve your desired effect by leveraging the start and stop events. Just add `$('"body").css('cursor', '......)` in an event handler.

The mouse down effect you're looking for can be achieved the easiest by changing up the items option to target your tables headers to an element inside of the table header like maybe a icon. There are other ways to handle this as well like maybe a button that creates an instance of dragtable on a target which to the user is known as "edit" mode most of the "solution"s to this problem are dictated by the design of your app / page.

**Comment by jackdeguest** [comment]
Wow, that was quick! Yes, this solved the problem, although I am still puzzled as to why.
There still is an issue with the width of the column header. For example, if you try to move col #2 to col #1, it will be moved, but the column width will remain.
For the drag vs sort click, yes, I guess I could put a div inside each th to act as a draggable area, but why not have a 1 to 2 second delay beyond which the dragging will start?

**Comment by jebaird** [comment]
The column width issue is due to how the css is setup. when the column is dragged, the plugin makes a copy of the col and sets the width. when the col is swapped it moves the original col in the table. since the drag display only has one col in it it will always get these styles

```
#content table tbody td:nth-child(1)
{
	width: 124px;
}
```

As for the delayed mouse down, The click and hold is a feature that's outside the scope of dragtable. However it is possible [see this fiddle for delayed mousedown](http://jsfiddle.net/LysCF/13/) How I would setup your effect is to add the delayed mousedown event binding. when the event is fired, initialize dragtable, trigger the mouse down event on the target column. After the dragstop event is fired, have it destroy the instance of the plugin.

**Comment by jackdeguest** [comment]
Thank you Jesse!
